//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dent
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DentbaseEntities : DbContext
    {
        public DentbaseEntities()
            : base("name=DentbaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Администраторы> Администраторы { get; set; }
        public virtual DbSet<Врачи> Врачи { get; set; }
        public virtual DbSet<Записи> Записи { get; set; }
        public virtual DbSet<История_записей> История_записей { get; set; }
        public virtual DbSet<Пользователи> Пользователи { get; set; }
        public virtual DbSet<Услуги> Услуги { get; set; }
    }
}
