//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Врачи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Врачи()
        {
            this.История_записей = new HashSet<История_записей>();

        }
        public Врачи(string Фамилия, string Имя, string Отчество, string Номер_телефона, string Пароль, string Стаж)
        {
            this.Фамилия = Фамилия;
            this.Имя = Имя;
            this.Отчество = Отчество;
            this.Номер_телефона = Номер_телефона;
            this.Пароль = Пароль;
            this.Стаж = Стаж;
        }

                    


        public int ID_врача { get; set; }
        public string Фамилия { get; set; }
        public string Имя { get; set; }
        public string Отчество { get; set; }
        public string Номер_телефона { get; set; }
        public string Пароль { get; set; }
        public string Стаж { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_записей> История_записей { get; set; }
    }
}
