//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dent
{
    using System;
    using System.Collections.Generic;
    
    public partial class Записи
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Записи()
        {
            this.История_записей = new HashSet<История_записей>();
            
        }
        public Записи(DateTime Дата)
        {
            this.Дата = Дата;
        }

        public int ID_Записи { get; set; }
        public System.DateTime Дата { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<История_записей> История_записей { get; set; }
    }
}
