//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dent
{
    using System;
    using System.Collections.Generic;
    
    public partial class История_записей
    {
        public История_записей()
        {
            

        }
        public История_записей(int ID_услуги, int ID_записи, int ID_пользователя, int ID_врача)
        {
            this.ID_услуги = ID_услуги;
            this.ID_записи = ID_записи;
            this.ID_пользователя = ID_пользователя;
            this.ID_врача = ID_врача;
            
        }
        public int ID_Истории { get; set; }
        public Nullable<int> ID_услуги { get; set; }
        public Nullable<int> ID_записи { get; set; }
        public Nullable<int> ID_пользователя { get; set; }
        public Nullable<int> ID_врача { get; set; }
        public string СтатусЗаписи { get; set; }
    
        public virtual Врачи Врачи { get; set; }
        public virtual Записи Записи { get; set; }
        public virtual Пользователи Пользователи { get; set; }
        public virtual Услуги Услуги { get; set; }
    }
}
